kind: ConfigMap
apiVersion: v1
metadata:
  name: csrx-config-map
data:
  csrx_license: |






  csrx_config: |
    interfaces {
     ge-0/0/0 {
        unit 0;
     }
     ge-0/0/1 {
        unit 0;
     }
    }
    security {
        policies {
            default-policy {
                permit-all;
            }
        }
        zones {
            security-zone trust {
                host-inbound-traffic {
                    system-services {
                        all;
                    }
                    protocols {
                        all;
                    }
                }
                interfaces {
                    ge-0/0/0.0;
                }
            }
            security-zone untrust {
                host-inbound-traffic {
                    system-services {
                        all;
                    }
                    protocols {
                        all;
                    }
                }
                interfaces {
                    ge-0/0/1.0;
                }
            }
        }
        nat {
            source {
                rule-set s-forward {
                    from zone trust;
                    to zone untrust;
                    rule s-forward-rule {
                        match {
                            source-address 0.0.0.0/0;
                        }
                        then {
                            source-nat {
                                interface;
                            }
                        }
                    }
                }
            }
            destination {
                pool forward-pool {
                    address 10.97.159.194/32 port 80;
                }
                rule-set forword {
                    from zone trust;
                    rule forward-rule {
                        match {
                            destination-address 0.0.0.0/0;
                            destination-port {
                                80;
                            }
                        }
                        then {
                            destination-nat {
                                pool {
                                    forward-pool;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    routing-options {
        static {
               route 10.97.159.194/32 next-hop 55.0.0.1;
        }
    }

