---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nw2-1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-21",
      "promiscMode": true,
      "ipam": {
          "type": "host-local",
          "ranges": [
              [
                 {
                     "subnet": "55.0.0.0/16",
                     "rangeStart": "55.0.0.11",
                     "rangeEnd": "55.0.0.20"
                 }
              ]
         ],
        "routes": [
                        { "dst": "0.0.0.0/0" }
                ]
      }
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: nw2-2
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-22",
      "promiscMode": true,
      "ipam": {
          "type": "host-local",
          "ranges": [
              [
                 {
                     "subnet": "66.0.0.0/16",
                     "rangeStart": "66.0.0.11",
                     "rangeEnd": "66.0.0.20"
                 }
              ]
         ],
                "routes": [
                        { "dst": "0.0.0.0/0" }
                ]
      }
    }'

